name: Deploying SIL Store to AWS Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to SIL_Store Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SIL_Store_PEM  }}
          host: ${{ secrets.SIL_Store_HOSTNAME  }}
          username: ${{ secrets.SIL_Store_USERNAME  }}
          script: |
            cd ~/SIL_Store
            ls
            git checkout main
            git pull ssh main
            pipenv shell
            pipenv install
            python3 manage.py makemigrations
            sudo systemctl restart sil_store.s*
            sudo systemctl restart nginx
